### PR TITLE
fix local variable referenced before assignment bugs

### PR DESCRIPTION
**Pull request by kristjanr**
Fixed  issue #69

### CODE REVIEW

**Comment by cpina** [comment]
Thanks - I had the same issue just right now and I'm happy that you submitted a fix yesterday.

Interestingly after applying your patch locally I have:
TransactionManagementError at /admin/csvimport/csvimport/add/
"An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block."

I haven't investigated but I wanted to thank you for the fix and ask you if you had this issue as well.

Cheers!

**Comment by cpina** [comment]
For my second error I've adapted this PR: https://github.com/edcrewe/django-csvimport/pull/38 and it worked for me (not fully tested but I don't have my second error, now fixing the CSV file)

**Comment by kristjanr** [comment]
Hi! Truth be told, I did see some kind of error after that, but after
verifiying that it is a different kind of error, I did the PR :P
Thank you for fixing and reacting so fast! I may now even use the package
in my project :)

**Comment by cpina** [comment]
@kristjanr : cool, but note that I'm just a user in the project that found it after you and found it usable thanks to your fix. I'm not involved in the project so I can't merge the PR or anything...

**Comment by edcrewe** [comment]
OK thanks, I guess it may be failing to detect a content type and hence not setting this variable.

**Comment by adamcooley** [comment]
Hey there running 2.9 and getting this error right now. Is this pushed yet?

**Pull request merged**
